from .config import db_host
from .config import db_name
from .config import db_user
from .config import db_pass
from .config import html_dir
from .config import url_location
from .config import pdf_dir
from .config import report_file
from .config import grade_file